sudo: false

language: ruby

before_install:
  - nvm install && nvm use

install:
  - bundle install
  - yarn install

script:
  - jekyll build --strict_front_matter --safe
  - jekyll doctor --safe
  - yarn test

notifications:
  email:
    on_success: never
    on_failure: change
